#+TITLE: Exercises

Individual exercises created for learning purposes.

- =99-lisp-problems=
  Solutions to the [[http://www.ic.unicamp.br/~meidanis/courses/mc336/2006s2/funcional/L-99_Ninety-Nine_Lisp_Problems.html][Ninety-Nine Lisp Problems from Unicamp]].

- =challenges=
  Loose code that implements simple things. You might want to take a look; maybe you'll discover something interesting.

- =erlang-tutorial=
  Exercises done in the official Erlang language tutorial.

- =incremental-economy-simulator=
  Incremental economy simulator game. Incomplete.

- =lfe-tutorial=
  Erlang tutorial, rewritten in LFE (Lisp-Flavored Erlang).

- =maratonas=
  Code created as solutions to Programming Marathons. Also includes code from URI Online Judge and SPOJ.

- =project-euler=
  Solutions to Project Euler problems in various languages. Tip: try solving it yourself before copying the solution. :)

- =quine=
  Implementation of a quine in Common Lisp.

- =rpn-calculator=
  Calculator in reverse Polish notation, written in F#.

- ~sml~
  Reading notes for the PDF /A Crash Course on Standard ML/.

- ~prolog~
  Experiments with the Prolog language.
