#+TITLE: EVA 1
#+AUTHOR: Lucas Samuel Vieira
#+LANGUAGE: pt-br
#+OPTIONS: toc:nil title:nil email:nil
#+STARTUP: latexpreview showall

:LATEX:
#+LATEX_CLASS: abntex2
#+LATEX_CLASS_OPTIONS: [article, a4paper, oneside, 11pt, english, brazil, sumario=tradicional]
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \usepackage[utf8x]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage[english, hyperpageref]{backref}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage{titling}

# Resolve problema de titulo estrangeiro
#+LATEX_HEADER: \ifthenelse{\equal{\ABNTEXisarticle}{true}}{%
#+LATEX_HEADER: \renewcommand{\maketitlehookb}{}
#+LATEX_HEADER: }{}

# Fontes de título
#+LATEX_HEADER: \titleformat{\section}{\normalfont\normalsize\bfseries\uppercase}{\thesection\space\space}{0pt}{}
#+LATEX_HEADER: \titleformat{\subsection}{\normalfont\normalsize\bfseries}{\thesubsection\space\space}{0pt}{\space}
#+LATEX_HEADER: \titleformat{\subsubsection}{\normalfont\normalsize\bfseries}{\thesubsubsection\space\space}{0pt}{\space}
#+LATEX_HEADER: \titleformat{\paragraph}{\normalfont\normalsize\itshape}{}{0pt}{\theparagraph\space\space}

# Bordas
#+LATEX_HEADER: \setlength{\parindent}{1.5cm}
#+LATEX_HEADER: \setlrmarginsandblock{3cm}{2cm}{*}
#+LATEX_HEADER: \setulmarginsandblock{2.5cm}{2.5cm}{*}
#+LATEX_HEADER: \checkandfixthelayout

#+LATEX: \OnehalfSpacing
#+LATEX: \pretextual
#+LATEX: \textual
:END:

#+begin_center
*UFVJM - UNIVERSIDADE FEDERAL DOS VALES DO JEQUITINHONHA E MUCURI*

*BACHARELADO EM SISTEMAS DE INFORMAÇÃO*

*BANCO DE DADOS II - SEMESTRE 2021/1*

*Exercício de Avaliação de Aprendizagem 1 - EVA 1*
#+end_center

#+LATEX: \noindent
Nome: Lucas Samuel Vieira
#+LATEX: \newline

# #+LATEX: \noindent
# Questões:
# #+LATEX: \newline

* Exercício 1

Formule e escreva 3 consultas aninhadas aplicadas às bases de dados utilizadas.

** Consulta aninhada 1

Realizada no banco de dados ~banco~.
Mostrar nome  e total  de empréstimos  de cada cliente  devedor que  tiver feito
empréstimos totalizando mais  de mil reais na agência de  Downtown, Brooklyn (ID
1).

#+header: :database banco
#+begin_src sql :tangle ex01-consulta01.sql
SELECT c.nome_cliente, e.total
  FROM cliente c
  JOIN devedor d
    ON c.cod_cliente = d.cod_cliente
  JOIN emprestimo e
    ON d.numero_emprestimo = e.numero_emprestimo
 WHERE c.cod_cliente IN
       (SELECT cod_cliente
          FROM devedor d
          JOIN emprestimo e
                ON d.numero_emprestimo = e.numero_emprestimo
         WHERE total > 1000
           AND d.cod_agencia = 1);
#+end_src

** Consulta aninhada 2

Realizada no banco de dados ~companhia~.
Mostrar  informações  de  empregados  que estejam  trabalhando  em  projetos  de
produtos com um gasto de mais de dez horas.

#+header: :database companhia
#+begin_src sql :tangle ex01-consulta02.sql
SELECT *
  FROM empregado e
 WHERE e.ssn IN
       (SELECT r.essn
          FROM projeto p
          JOIN trabalha_em r
                ON r.pno = p.pnumero
         WHERE p.pjnome LIKE 'Produto%'
           AND r.horas > 10)
#+end_src

** Consulta aninhada 3

Realizada no banco de dados ~concurso~.
Mostrar todos  os candidatos  cujo preço  de inscrição  esteja entre  os maiores
preços de inscrição para a cidade de Formiga.

#+header: :database concurso
#+begin_src sql :tangle ex01-consulta03.sql
SELECT DISTINCT c.*
  FROM inscricao i
  JOIN candidato c
    ON i.cod_candidato = c.cod_candidato
  JOIN tipo_inscricao ti
    ON i.tipo_inscricao = ti.cod_tipo
 WHERE ti.preco IN
       (SELECT DISTINCT ti.preco
          FROM inscricao i
          JOIN tipo_inscricao ti
                ON i.tipo_inscricao = ti.cod_tipo
          JOIN municipio m
                ON i.cod_municipio = m.cod_municipio
         WHERE m.descricao = 'Formiga'
           AND ti.preco > 25)
#+end_src

* Exercício 2

Formule e escreva  2 stored procedures (1  delas com uso de  parâmetros) sobre a
base de dados ~concurso~.

** Procedure 1

Lista os dados dos candidatos de cada inscrição, juntamente com o município para
o qual se inscreveram.

#+begin_src sql :tangle ex02-procedure01.sql
DELIMITER &
CREATE PROCEDURE sp_lista_inscricoes_candidatos()
BEGIN
        SELECT i.cod_inscricao AS codigo,
               m.descricao AS municipio_nome,
               c.nome, c.cpf, c.telefone, c.endereco
          FROM inscricao i
          JOIN candidato c
            ON i.cod_candidato = c.cod_candidato
          JOIN municipio m
            ON i.cod_municipio = m.cod_municipio;
END &
DELIMITER ;
#+end_src

** Procedure 2

Coleta a quantidade de inscrições realizadas para um município em específico.

#+begin_src sql :tangle ex02-procedure02.sql
DELIMITER &
CREATE PROCEDURE sp_num_insc_por_mun(out num_insc int, mun_desc VARCHAR(20))
BEGIN
        SELECT count(*) into num_insc
          FROM inscricao i
          JOIN municipio m
            ON i.cod_municipio = m.cod_municipio
           AND m.descricao = mun_desc;
END &
DELIMITER ;
#+end_src

* Exercício 3

Formule e escreva 3  visões, 1 em cada base de dados  utilizada. Todas as visões
devem  utilizar-se de  alguma  função  de agregação  (~count~,  ~sum~, ~min~  ou
~max~).

** Visão 1

Criada no banco de dados ~banco~.
Mostra o saldo total  de cada cliente, juntamente com seus dados,  e o número de
contas que o mesmo possui.

#+begin_src sql :tangle ex03-visao01.sql
CREATE VIEW vw_clientes_saldo_total AS
SELECT c.cod_cliente, c.nome_cliente, c.rua_cliente,
       c.cidade_cliente,
       count(dt.numero_conta) AS num_contas,
       sum(ct.saldo) AS saldo_total
  FROM devedor d
  JOIN cliente c
    ON c.cod_cliente = d.cod_cliente
  JOIN depositante dt
    ON dt.cod_cliente = c.cod_cliente
  JOIN conta ct
    ON dt.numero_conta = ct.numero_conta
  GROUP BY c.cod_cliente;
#+end_src

** Visão 2

Criada no banco de dados ~companhia~.
Mostra os dados dos empregados, a quantidade de horas empregadas em projetos e a
quantidade de projetos de que o mesmo participa.

#+begin_src sql :tangle ex03-visao02.sql
CREATE VIEW vw_empregados_horas_projetos AS
SELECT e.nome, e.ssn, e.datanasc, e.endereco, e.sexo,
       e.salario,
       sum(coalesce(r.horas, 0)) AS horas_projetos,
       count(p.pnumero) as num_projetos
  FROM empregado e
  JOIN trabalha_em r
    ON e.ssn = r.essn
  JOIN projeto p
    ON r.pno = p.pnumero
  GROUP BY e.ssn;
#+end_src

** Visão 3

Criada no banco de dados ~concurso~.
Mostra a quantidade de inscrições realizadas para cada município.

#+begin_src sql :tangle ex03-visao03.sql
CREATE VIEW vw_inscricoes_municipio AS
SELECT m.*, count(i.cod_inscricao) AS num_inscricoes
  FROM municipio m
  JOIN inscricao i
    ON m.cod_municipio = i.cod_municipio
  GROUP BY m.cod_municipio;
#+end_src

* Exercício 4

Formule e escreva 2 funções a serem  aplicadas em quaisquer bases de dados. Pelo
menos 1 função deve conter declaração de variável e estrutura condicional em seu
código.

** Função 1

Criada no banco de dados ~concurso~.
Mostra  a rentabilidade  do  valor arrecadado  com os  concursos  para a  cidade
indicada, na forma de conceito (alto, médio, baixo).

#+begin_src sql :tangle ex04-funcao01.sql
DELIMITER &
CREATE FUNCTION f_rentabilidade(municipio varchar(20)) RETURNS varchar(12)
BEGIN
  DECLARE valor float;

  SELECT sum(ti.preco) INTO valor
    FROM municipio m
    JOIN inscricao i
      ON i.cod_municipio = m.cod_municipio
    JOIN tipo_inscricao ti
      ON i.tipo_inscricao = ti.cod_tipo
   WHERE m.descricao = municipio;

  CASE
    WHEN (valor <= 300)
         THEN RETURN 'BAIXO';     
    WHEN (valor > 300 AND valor < 500)
         THEN RETURN 'MEDIO';
    WHEN (valor >= 500)
         THEN RETURN 'ALTO';
    ELSE RETURN 'DESCONHECIDO';
  END CASE;
END &
DELIMITER ;
#+end_src

** Função 2

Criada no banco de dados ~companhia~.
Mostra  a  quantidade  de  horas  empregadas  por  funcionários  em  um  projeto
específico, no total.

#+begin_src sql :tangle ex04-funcao02.sql
DELIMITER &
CREATE FUNCTION f_horasempregadas(proj varchar(20)) RETURNS float
BEGIN
        DECLARE t_horas float;

        SELECT sum(horas) INTO t_horas
          FROM projeto p
          JOIN trabalha_em r
            ON r.pno = p.pnumero
         WHERE p.pjnome = proj;

    RETURN t_horas;
END &
DELIMITER ;
#+end_src

