
(DEFPARAMETER *TEMPLATE*
  '(PROGN
    (DEFMACRO ENIUQ ()
      `((DEFPARAMETER *TEMPLATE* '(,@*TEMPLATE*))
        (DEFUN QUINE ()
          (EVAL *TEMPLATE*)
          (MAPC #'PRINT (MACROEXPAND '(ENIUQ)))))))) 
(DEFUN QUINE () (EVAL *TEMPLATE*) (MAPC #'PRINT (MACROEXPAND '(ENIUQ)))) 
