#+title: Bancos de Dados II
#+author: Lucas S. Vieira
#+PROPERTY: header-args:sql :engine mysql :dbport 3306 :dbuser root :dbpassword senha :dbhost 172.17.0.2 :exports both

Bancos de dados usados na disciplina.

* Banco de dados

** Criando o BD com Docker

Isso vai criar o SGBD para a disciplina.

#+begin_src bash
docker pull mariadb/server:10.5
docker run --detach \
       --name dbms-bd2 \
       -p 3306:3306 \
       --env MYSQL_ROOT_PASSWORD="senha" \
       -v "$(pwd)"/scripts:/scripts \
       mariadb/server:10.5
#+end_src

Scripts estarão em ~/scripts~.

** Conectar via console

Descobrir o IP do BD:

#+begin_src bash :exports both
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dbms-bd2
#+end_src

Conectar através do console:

#+begin_src bash
docker exec -it dbms-bd2 mysql -uroot -psenha
#+end_src

Se precisar acessar o filesystem:

#+begin_src bash
docker exec -it dbms-bd2 bash
#+end_src

** Rodando o script

Para rodar o script, abrir o mysqli e executar:

#+begin_src fundamental
mysql> source /scripts/bases_dados.sql
#+end_src


* Comandos de privilégios de acesso

** Criação de usuário

#+begin_src sql
CREATE USER 'usuario'@'%' IDENTIFIED BY 'senha';
#+end_src

O  wildcard após  o ~@~  indica que  o usuário  poderá se  conectar de  qualquer
host. Poderia ser substituído por um IP em específico, por exemplo.

** Adição de permissões

#+begin_src sql
GRANT lista_de_privilegios ON nivel_de_privilegios TO usuario opcao_de_grant;
#+end_src

Exemplos:

#+begin_src sql
GRANT ALL PRIVILEGES ON *.* TO 'usuario'@'%';
GRANT ALL PRIVILEGES ON empresa.* TO 'usuario'@'%';
#+end_src

** Revogação de permissões

#+begin_src sql
REVOKE lista_de_privilegios ON nivel_de_privilegios FROM usuario;
#+end_src

Exemplo:

#+begin_src sql
REVOKE ALL PRIVILEGES ON *.* FROM 'usuario'@'%';
#+end_src

** Lista de privilégios

Exemplos possíveis para lista de privilégios:

- ALL [PRIVILEGES]
- ALTER
- CREATE
- DELETE
- DROP
- EXECUTE
- FILE
- INDEX
- INSERT
- SELECT
- SHOW DATABASES
- SHUTDOWN
- UPDATE
- USAGE
- ...

** Nível de privilégios


